# Generated by Django 5.0.6 on 2026-03-18 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('venue', models.CharField(max_length=200, verbose_name='Lugar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Vendidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event')),
            ],
            options={
                'verbose_name': 'Tipo de Entrada',
                'verbose_name_plural': 'Tipos de Entrada',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nombre del comprador')),
                ('buyer_email', models.CharField(max_length=200, verbose_name='Email')),
                ('buyer_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(default='efectivo', max_length=50, verbose_name='Medio de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('used', 'Usada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/', verbose_name='QR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_sold', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-created_at'],
            },
        ),
    ]
